# Generated by Django 5.2 on 2025-09-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailCampaign',
            new_name='BrandGuideline',
        ),
    ]
