# Generated by Django 5.2 on 2025-09-02 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_emailcampaign_to_brandguideline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brandguideline',
            name='guideline_type',
            field=models.CharField(choices=[('tone', 'Tone of Voice'), ('terminology', 'Company Terminology'), ('style', 'Writing Style'), ('rules', 'Content Rules')], default='tone', max_length=20),
        ),
        migrations.AlterField(
            model_name='brandguideline',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_guidelines', to=settings.AUTH_USER_MODEL),
        ),
    ]
