# Generated by Django 5.2 on 2025-09-02 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_guideline_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('txt', 'Text'), ('json', 'JSON')], max_length=10)),
                ('raw_content', models.TextField()),
                ('parsed_campaigns', models.JSONField(blank=True, default=list)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('campaign_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date', '-id'],
            },
        ),
    ]
