# Generated by Django 5.2 on 2025-09-05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_add_linkedin_scrape"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustpilotScrape",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(max_length=500)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trustpilot_scrapes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="trustpilotscrape",
            index=models.Index(fields=["user", "url"], name="api_tp_user_url_idx"),
        ),
        migrations.AddIndex(
            model_name="trustpilotscrape",
            index=models.Index(fields=["user", "created_at"], name="api_tp_user_created_idx"),
        ),
    ]


