# Generated by Django 5.2 on 2025-09-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_website_scrape'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='linkedinscrape',
            new_name='api_linkedi_user_id_134373_idx',
            old_name='api_linkedin_user_url_idx',
        ),
        migrations.RenameIndex(
            model_name='linkedinscrape',
            new_name='api_linkedi_user_id_5265d9_idx',
            old_name='api_linkedin_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='trustpilotscrape',
            new_name='api_trustpi_user_id_ab4b88_idx',
            old_name='api_tp_user_url_idx',
        ),
        migrations.RenameIndex(
            model_name='trustpilotscrape',
            new_name='api_trustpi_user_id_8f833b_idx',
            old_name='api_tp_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='websitescrape',
            new_name='api_website_user_id_a57f02_idx',
            old_name='api_site_user_created_idx',
        ),
    ]
